# Generated by Django 5.0.4 on 2024-05-07 01:56

import client_portal.users.storage
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=511)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile_picture', models.FileField(blank=True, null=True, storage=client_portal.users.storage.UserStorage(), upload_to=client_portal.users.storage.UserStorageFolder)),
                ('deleted', models.DateTimeField(null=True)),
                ('permissions', models.ManyToManyField(to='users.userpermission')),
            ],
        ),
    ]
